#include "audio_core/analysis/golden_master.hpp"
#include <iostream>
#include <vector>
#include <string>
#include <iomanip>
#include <filesystem>
#include <chrono>

using namespace audio_core::analysis;

int main(int argc, char* argv[]) {
    bool verify_mode = false;
    bool generate_mode = false;
    bool render_wavs = false;
    std::string wav_dir = "renders/golden_masters";

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--verify") {
            verify_mode = true;
        } else if (arg == "--generate") {
            generate_mode = true;
        } else if (arg == "--render-wavs") {
            render_wavs = true;
            if (i + 1 < argc && argv[i + 1][0] != '-') {
                wav_dir = argv[++i];
            }
        } else if (arg == "--help" || arg == "-h") {
            std::cout << "Usage: golden_master_tool [OPTIONS]\n"
                      << "Options:\n"
                      << "  --verify       Verify audio output against embedded golden master references\n"
                      << "  --generate     Compute actual values and print C++ reference definitions\n"
                      << "  --render-wavs  Export 24-bit PCM reference WAVs to directory (default: renders/golden_masters/)\n"
                      << "  --help         Show this help message\n";
            return 0;
        }
    }

    std::cout << "========================================================================================\n";
    std::cout << "          AUDIO-ENGINE-CORE // AUTOMATED GOLDEN MASTER AUDIO CHECKSUM SUITE             \n";
    std::cout << "========================================================================================\n\n";

    auto pipelines = GoldenMasterSuite::create_canonical_pipelines();

    if (render_wavs) {
        std::filesystem::create_directories(wav_dir);
        std::cout << "[INFO] Exporting 24-bit PCM Reference WAVs to: " << wav_dir << "\n\n";
    }

    auto start_time = std::chrono::high_resolution_clock::now();
    std::vector<GoldenMasterMetrics> results;
    results.reserve(pipelines.size());

    for (const auto& pipe : pipelines) {
        std::vector<float> left;
        std::vector<float> right;
        pipe.render_func(left, right);

        GoldenMasterMetrics m = GoldenMasterAnalyzer::analyze(
            pipe.name, left.data(), right.data(), pipe.frames, pipe.sample_rate);
        results.push_back(m);

        if (render_wavs) {
            std::string wav_path = wav_dir + "/" + pipe.name + ".wav";
            audio_core::sampling::WavReader::save_wav(
                wav_path, left.data(), right.data(), pipe.frames, pipe.sample_rate, 24);
        }
    }

    auto end_time = std::chrono::high_resolution_clock::now();
    double total_ms = std::chrono::duration<double, std::milli>(end_time - start_time).count();

    if (generate_mode) {
        std::cout << "// ============================================================================\n";
        std::cout << "// CANONICAL GOLDEN MASTER REFERENCE TABLE (Generated by golden_master_tool)\n";
        std::cout << "// ============================================================================\n";
        std::cout << "struct CanonicalReference {\n"
                  << "    const char* name;\n"
                  << "    size_t frames;\n"
                  << "    uint64_t fnv1a64;\n"
                  << "    uint32_t crc32;\n"
                  << "    float peak_dbfs;\n"
                  << "    float rms_dbfs;\n"
                  << "    float crest_factor_db;\n"
                  << "    uint32_t zero_crossings;\n"
                  << "};\n\n";
        std::cout << "inline constexpr CanonicalReference kCanonicalGoldenMasters[" << results.size() << "] = {\n";
        for (size_t i = 0; i < results.size(); ++i) {
            const auto& r = results[i];
            std::cout << "    {\n"
                      << "        \"" << r.pipeline_name << "\",\n"
                      << "        " << r.frames << "ULL,\n"
                      << "        0x" << std::hex << std::uppercase << r.pcm24_fnv1a64 << "ULL,\n"
                      << "        0x" << std::hex << std::uppercase << r.pcm24_crc32 << "U,\n"
                      << "        " << std::dec << std::fixed << std::setprecision(4) << r.peak_dbfs << "f,\n"
                      << "        " << std::dec << std::fixed << std::setprecision(4) << r.rms_dbfs << "f,\n"
                      << "        " << std::dec << std::fixed << std::setprecision(4) << r.crest_factor_db << "f,\n"
                      << "        " << r.zero_crossings << "U\n"
                      << "    }" << (i + 1 < results.size() ? "," : "") << "\n";
        }
        std::cout << "};\n\n";
        std::cout << "// Generated " << results.size() << " pipelines in " << total_ms << " ms\n";
        return 0;
    }

    if (verify_mode) {
        std::vector<GoldenMasterDiff> diffs;
        bool all_passed = GoldenMasterSuite::verify_all(&diffs);

        std::cout << std::left << std::setw(38) << "Pipeline Name"
                  << std::setw(10) << "Status"
                  << std::setw(20) << "Expected FNV64"
                  << std::setw(20) << "Actual FNV64"
                  << "\n";
        std::cout << std::string(88, '-') << "\n";

        for (const auto& d : diffs) {
            std::cout << std::left << std::setw(38) << d.pipeline_name
                      << std::setw(10) << (d.passed ? "[PASS]" : "[FAIL]")
                      << "0x" << std::hex << std::uppercase << std::setw(18) << std::setfill('0') << d.expected_fnv64
                      << "0x" << std::hex << std::uppercase << std::setw(18) << std::setfill('0') << d.actual_fnv64
                      << std::dec << std::setfill(' ')
                      << "\n";
            if (!d.passed) {
                std::cout << "  -> " << d.format_report() << "\n";
            }
        }
        std::cout << std::string(88, '-') << "\n";
        if (all_passed) {
            std::cout << "[SUCCESS] All " << diffs.size() << " canonical golden masters verified bit-exact!\n";
            return 0;
        } else {
            std::cerr << "[ERROR] Audio golden master regression detected!\n";
            return 1;
        }
    }

    // Default output table
    std::cout << std::left << std::setw(38) << "Pipeline Name"
              << std::setw(8) << "Frames"
              << std::setw(12) << "Peak dBFS"
              << std::setw(12) << "RMS dBFS"
              << std::setw(20) << "PCM24 FNV-1a 64"
              << std::setw(12) << "CRC-32"
              << std::setw(10) << "Status"
              << "\n";
    std::cout << std::string(112, '-') << "\n";

    for (const auto& r : results) {
        std::cout << std::left << std::setw(38) << r.pipeline_name
                  << std::setw(8) << r.frames
                  << std::fixed << std::setprecision(2) << std::setw(12) << r.peak_dbfs
                  << std::fixed << std::setprecision(2) << std::setw(12) << r.rms_dbfs
                  << "0x" << std::hex << std::uppercase << std::setw(18) << std::setfill('0') << r.pcm24_fnv1a64
                  << "0x" << std::setw(10) << std::setfill('0') << r.pcm24_crc32
                  << std::dec << std::setfill(' ') << std::setw(10) << "OK"
                  << "\n";
    }

    std::cout << std::string(112, '-') << "\n";
    std::cout << "[BENCHMARK] Executed " << results.size() << " pipelines ("
              << 69632 << " frames) in " << std::fixed << std::setprecision(3) << total_ms
              << " ms (" << (69632.0 / (total_ms * 0.001) / 1000000.0) << " MFrames/sec)\n\n";

    if (render_wavs) {
        std::cout << "[SUCCESS] 10 Golden Master WAV files written to: " << wav_dir << "\n";
    }

    return 0;
}
